version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - aldostores-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node_backend
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    networks:
      - aldostores-network
    command: >
      sh -c "
      npm install ts-node -g &&
      ts-node ./db_setup.ts &&
      npm run build &&
      npm start
      "

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_frontend
    environment:
      REACT_APP_BACKEND_URL: http://backend:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - aldostores-network
  
networks:
  aldostores-network:

volumes:
  postgres-data:
