version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - aldostores-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  aldostores-network:

volumes:
  postgres-data:
